/// Helper function to thoroughly sanitize text generated by AI models.
/// Removes raw markdown headers (##, #), bold asterisks (**), bullets, and symbol artifacts.
String cleanAiText(String? input) {
  if (input == null) return '';
  var text = input;

  // Remove markdown code fences if any
  text = text.replaceAll(RegExp(r'```[a-zA-Z]*\n?'), '').replaceAll('```', '');

  // Remove markdown headers (##, ###, #) at line start or anywhere
  text = text.replaceAllMapped(RegExp(r'(^|\n)\s*#+\s*'), (m) => m[1] ?? '');
  text = text.replaceAll(RegExp(r'#+'), '');

  // Remove bold / italic symbols (**text** or *text* or __text__)
  text = text.replaceAllMapped(RegExp(r'\*\*([^*]+)\*\*'), (m) => m[1] ?? '');
  text = text.replaceAllMapped(RegExp(r'\*([^*]+)\*'), (m) => m[1] ?? '');
  text = text.replaceAllMapped(RegExp(r'__([^_]+)__'), (m) => m[1] ?? '');
  text = text.replaceAllMapped(RegExp(r'_([^_]+)_'), (m) => m[1] ?? '');

  // Remove backticks
  text = text.replaceAllMapped(RegExp(r'`([^`]+)`'), (m) => m[1] ?? '');
  text = text.replaceAll('`', '');

  // Remove leading bullet dashes or asterisks
  text = text.replaceAllMapped(RegExp(r'(^|\n)\s*[-*•]\s+'), (m) => m[1] ?? '');

  // Collapse multiple extra spaces/newlines
  text = text.replaceAll(RegExp(r'[ \t]+'), ' ');
  return text.trim();
}

class TripRequest {
  final String destination;
  final String startDate;
  final String endDate;
  final int travelers;
  final String budgetLevel;
  final List<String> interests;
  final String provider;

  TripRequest({
    required this.destination,
    required this.startDate,
    required this.endDate,
    required this.travelers,
    required this.budgetLevel,
    required this.interests,
    required this.provider,
  });

  Map<String, dynamic> toJson() => {
        'destination': destination,
        'start_date': startDate,
        'end_date': endDate,
        'travelers': travelers,
        'budget_level': budgetLevel,
        'interests': interests,
        'provider': provider,
      };
}

class ItineraryActivity {
  final String time;
  final String activity;
  final String? location;
  final String? notes;

  ItineraryActivity({
    required this.time,
    required this.activity,
    this.location,
    this.notes,
  });

  factory ItineraryActivity.fromJson(Map<String, dynamic> json) => ItineraryActivity(
        time: cleanAiText(json['time'] as String? ?? 'Anytime'),
        activity: cleanAiText(json['activity'] as String? ?? ''),
        location: json['location'] != null ? cleanAiText(json['location'] as String) : null,
        notes: json['notes'] != null ? cleanAiText(json['notes'] as String) : null,
      );
}

class ItineraryDay {
  final int day;
  final String? date;
  final List<ItineraryActivity> activities;

  ItineraryDay({required this.day, this.date, required this.activities});

  factory ItineraryDay.fromJson(Map<String, dynamic> json) => ItineraryDay(
        day: json['day'] as int? ?? 1,
        date: json['date'] as String?,
        activities: (json['activities'] as List? ?? [])
            .map((a) => ItineraryActivity.fromJson(a as Map<String, dynamic>))
            .toList(),
      );
}

class ItineraryResponse {
  final String destination;
  final String providerUsed;
  final String? summary;
  final List<ItineraryDay> days;

  ItineraryResponse({
    required this.destination,
    required this.providerUsed,
    this.summary,
    required this.days,
  });

  factory ItineraryResponse.fromJson(Map<String, dynamic> json) => ItineraryResponse(
        destination: cleanAiText(json['destination'] as String? ?? 'Trip'),
        providerUsed: json['provider_used'] as String? ?? 'AI',
        summary: json['summary'] != null ? cleanAiText(json['summary'] as String) : null,
        days: (json['days'] as List? ?? [])
            .map((d) => ItineraryDay.fromJson(d as Map<String, dynamic>))
            .toList(),
      );
}
